### ISSUE TITLE
There's no way to securely use this action to only approve dependency updates

### ISSUE THREAD

**Issue by nate-selzer** [hmarr/auto-approve-action#171]
Anyone with write access to the repo who wants to bypass code review requirements can effectively do so by adding a github action that approves their PR. I think this should be clearly documented near the dependabot use-case (unless there's something I'm unaware of that can be done to prevent this).

**Comment by alexwilson** [comment]
This may now be resolved by a recent change GitHub have made, which nudges actions like this one to be run via `pull_request_target` as opposed to `pull_request`: https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/

**Comment by hmarr** [comment]
Yup, this action will only have permission to add the review if it's triggered by an event like `pull_request_target`, which has a write-access GitHub token. In general, people ought to be using branch protection and codeowners to prevent rogue workflows making their way onto important branches.
