### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by wesleyjconnorsesame** [hmarr/auto-approve-action#180]
[Recently](url) (last 2 weeks)
This action has started failing frequently in our builds, the only error being 'Not Found' there is no indication what is not found
Often retrying fixes this, however previously this was working very reliably
![auto-approve](https://user-images.githubusercontent.com/61691521/106452517-4a4fb680-6488-11eb-88c6-faa481e8da12.png)

**Comment by skjnldsv** [comment]
We have `Resource not accessible by integration` now, super weird :thinking: 
@hmarr , any clue? :)

**Comment by alexwilson** [comment]
This is a result of some changes GitHub recently made to improve the security of actions:
Blog post: https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
Documentation: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target

I'm trying to diagnose the full problem for another action here: https://github.com/alexwilson/enable-github-automerge-action/issues/18

**Comment by chrisgilmerproj** [comment]
@skjnldsv and @alexwilson - I think this issue deserves its own issue and a PR that updates the example docs. I'm also fighting this change today and probably the larger community is too.

**Comment by hmarr** [comment]
@skjnldsv I've responded to the question about the `Resource not accessible by integration` issue in #183 – let me know if that works for you!

@wesleyjconnorsesame is this still happening? If so, are you able to link to an example in a public repository?

**Comment by hmarr** [comment]
@wesleyjconnorsesame I think the mostly likely cause of a 404 would be the access token not having access to the repository. If you're using a personal access token, check the scopes on the token to make sure the token has access to the repository.

I added a more descriptive error message in https://github.com/hmarr/auto-approve-action/commit/eeecb82600f1437654cd6fde109fcdf6fc97e271.
