### ISSUE TITLE
Action passes when GH Token Access fails

### ISSUE THREAD

**Issue by bennycode** [hmarr/auto-approve-action#193]
I was a bit confused that the action passed even though I forgot to add a GitHub token to my "Secrets":

![image](https://user-images.githubusercontent.com/469989/160020474-47dadc60-3595-4f19-8d02-bdf0a8d045cf.png)

When the action has an error it should actually throw that error and make the build step fail.

**Comment by hmarr** [comment]
Thanks for reporting, should be fixed now
