### ISSUE TITLE
Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead"

### ISSUE THREAD

**Issue by nxp923** [hmarr/auto-approve-action#198]
Our workflow job failing since new changes added to the code. It's failing load auto-approe-action and throwing below error. 

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.'). 

and also tried to use below action in our workflow to install node16
- uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm install

**Comment by hmarr** [comment]
It looks like the default version [is now `node16`](https://github.blog/changelog/2021-12-10-github-actions-github-hosted-runners-now-run-node-js-16-by-default/). Are you using self-hosted runners, by any chance? It looks like `node16` is available [if you're using GHES 3.4](https://docs.github.com/enterprise-server@3.4/admin/release-notes#github-actions-changes) or later.

In the meantime, pinning to `v2.1.0` (`uses: hmarr/auto-approve-action@v2.1.0`) will take you back to the `node12` based version.

**Comment by nxp923** [comment]
Thanks Harry for replying. 
v2.1.0 does not accept PR# as an input it takes only one input param i.e. github token. In our case it will not work. 
and our GHES is 3.2 version. 
Any other suggestions?
Appreciate your help.

**Comment by hmarr** [comment]
I just tested the recent changes with Node 12 and they seemed to work, so I [reverted](https://github.com/hmarr/auto-approve-action/commit/24ec4c8cc344fe1cdde70ff37e55ace9e848a1d8) to Node 12.

Can you check that the `v2` branch works? I'll cut a new release if so.

**Comment by nxp923** [comment]
Thanks Harry for the quick help. It resolved our issue.
