### ISSUE TITLE
Autoaprove self PR create by script

### ISSUE THREAD

**Issue by vschoener** [hmarr/auto-approve-action#199]
Hello,

I have a case where I would like to auto-approve a PR created by a script. But not sure the auto approve will work using the same CIRCLECI TOKEN that was used to create the PR

Do you have an idea about that?

Thank you

**Comment by hmarr** [comment]
I don't believe you can approve your own pull request (even as a bot). See https://github.com/hmarr/auto-approve-action/issues/66 for more details. I presume you mean GitHub token rather than CircleCI token?

**Comment by JoseLion** [comment]
I don't think this is completely true. I use this action to approve my own PRs. You need to be sure you have this setting enabled:
- Go to the  repo **Settings**
- Find **Actions** tab
- Go to **Workflow permissions** section
- Check **Allow GitHub Actions to create and approve pull requests** box
- Click the **Save** button

![image](https://github.com/hmarr/auto-approve-action/assets/3087228/ee8bc07d-b5a0-4f45-b358-8821a0a6fd1c)

**Comment by JoseLion** [comment]
@hmarr maybe that should be part of the documentation, a `Troubleshooting` section perhaps? What do you think? 🙂

**Comment by hmarr** [comment]
@JoseLion happy to mention it in the docs. I'm not sure I fully get the problem though, so if you want to write the "if you're trying to do x, but you get error y, do z" form (either here or in a PR) I'm happy to include it.
