### ISSUE TITLE
GitHub Personal Access Token: What access is needed?

### ISSUE THREAD

**Issue by mushlih-almubarak** [hmarr/auto-approve-action#203]
Hi, it says in your documentation:
"To approve the pull request as a different user, pass a GitHub Personal Access Token into the github-token input"
My question is, what access does this action need?

**Comment by hmarr** [comment]
I just [added this information to the README](https://github.com/hmarr/auto-approve-action/commit/1cac024a6522bc746ff2796dffd4537db1f37425), hopefully that clears it up

**Comment by mushlih-almubarak** [comment]
Thanks for the answer, but I've tried it and it doesn't work, the error is: `Bad credentials. Please check that the 'github-token' input parameter is set correctly.`

I have added an access token with the `repo` scope and then added it as `repository secrets` with the name `PAT` on the repo settings page, then I added `github-token: ${{ secrets.PAT }}` in the configuration file, but it still doesn't work and the error appears as above.

Have you tested this on your side and it works?

Any help is greatly appreciated, thanks!

**Comment by hmarr** [comment]
Is this in response to a Dependabot pull request?

I just [added a note](https://github.com/hmarr/auto-approve-action/commit/b0011f5689ebf3715c5156d34498fde052693a67) about that to the README too.
