### ISSUE TITLE
Upgrade node version to 20

### ISSUE THREAD

**Issue by Gershon-A** [hmarr/auto-approve-action#224]
Node 12 and 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases), prompting us to initiate its deprecation process for GitHub Actions. Our plan is to transition all actions to run on Node 20 by Spring 2024. We will actively monitor the migration's progress and gather community feedback before finalizing the transition date. Starting October 23rd, workflows containing actions running on Node 16 will display a warning to alert users about the upcoming migration.

**Comment by hmarr** [comment]
I've just published v4.0.0, which switches from node 16 to node 20
