### ISSUE TITLE
GITHUB_TOKEN should be checked, but should it be created too ?

### ISSUE THREAD

**Issue by tristanbes** [hmarr/auto-approve-action#3]
Hello,

It may sound like a dumb question but on the doc it says `GITHUB_TOKEN` should be checked.

Should we create too using "create a new secret" ? If yes, which permission are required for this TOKEN ? should it be created using a particular account ? 

Thank you :)

ping @greysteil

**Comment by hmarr** [comment]
You don't need to create a new secret - that's for adding other (non-GitHub) secrets to the action runtime environment. Just checking the box should suffice.
