### ISSUE TITLE
Syntax error when using this action

### ISSUE THREAD

**Issue by tristanbes** [hmarr/auto-approve-action#4]
Hi,

When using this role, it leads to a syntax error. I don't know what I did wrong though.

![Editing_condictio_main_workflow_at_tristanbes-patch-1_·_Yproximite_condictio](https://user-images.githubusercontent.com/346010/61370359-84e80300-a892-11e9-935e-8b859cea25e3.png)

```
workflow "Auto Approve" {
  on = "pull_request"
  resolves = ["hmarr/auto-approve-action"]
}

action "Filters for GitHub Actions" {
  uses = "actions/bin/filter@3c0b4f0e63ea54ea5df2914b4fabf383368cd0da"
  args = "actor dependabot[bot]"
}

action "hmarr/auto-approve-action" {
  uses = "hmarr/auto-approve-action"
  needs = ["Filters for GitHub Actions"]
  secrets = ["GITHUB_TOKEN"]
}
```

Error is the following: 

```
Parse error
Line 12: The `uses' attribute must be a path, a Docker image, or owner/repo@ref
```

### Solution:

You need to edit: 
`  uses = "hmarr/auto-approve-action"`
to 
`  uses = "hmarr/auto-approve-action@master"` (if you want to use the master branch)

**Comment by tristanbes** [comment]
ping @greysteil 
I think this could be improved when using external predefined actions, the visual editor should be able to display a `ref` selector defaulting to the master branch for example.

It'll lead to this kind of tickets I think for new users "importing" GithubActions from the community with no ability to edit visually the `ref`.

IMO, without specifying `@master` it should silently defaults to it. What do you think ? (not sure this kind of feedback should be sent there btw).

**Comment by greysteil** [comment]
This is the right place! @hmarr is in Colombia so will pick it up when he wakes up!

**Comment by hmarr** [comment]
Yeah, this isn't super clear, but it's an Actions-wide issue. I've passed the feedback along to the Actions team and they're aware of the confusion.

In the meantime I've [updated the README](https://github.com/hmarr/auto-approve-action/commit/0b1181b7691b73f11a607555bf3df0709c190fb8) to be clearer.
