### ISSUE TITLE
##[error]Unprocessable Entity

### ISSUE THREAD

**Issue by Ryukote** [hmarr/auto-approve-action#85]
What should this error means?

**Comment by juanpedromoreno** [comment]
In my case, it happened when trying to use the same bot for creating and approving a PR. As that's not possible in Github, you need to use different accounts for each action.

**Comment by hmarr** [comment]
I just reproduced this - it does indeed happen when a user tries to approve their own PR. I added a more helpful error message in e21ecf1.
